#!/bin/bash

echo "🔍 Scanning Areas/Learning/ for legacy structures..."

if [ ! -d "Areas/Learning" ]; then
  echo "✅ No Areas/Learning/ directory found. Nothing to migrate."
  exit 0
fi

cd Areas/Learning

mkdir -p Lessons

MIGRATED_COUNT=0

for item in *; do
  if [ "$item" != "Lessons" ] && [ "$item" != "Resources" ] && [ "$item" != "README.md" ]; then
    echo "📦 Moving $item -> Lessons/$item"
    mv "$item" Lessons/
    MIGRATED_COUNT=$((MIGRATED_COUNT+1))
  fi
done

# If README.md exists and doesn't contain the Master Index keyword, it's likely the old index
if [ -f "README.md" ] && ! grep -q "Master Index" README.md && ! grep -q "Phân nhóm Tri thức" README.md; then
  echo "📦 Moving legacy README.md -> Lessons/README.md"
  mv README.md Lessons/
  MIGRATED_COUNT=$((MIGRATED_COUNT+1))
fi

if [ $MIGRATED_COUNT -gt 0 ]; then
  echo "✅ Migrated $MIGRATED_COUNT legacy items to Areas/Learning/Lessons/."
  
  # Create a Master Index if it doesn't exist
  if [ ! -f "README.md" ]; then
    echo "📝 Creating new Master Index at Areas/Learning/README.md"
    cat << 'EOF' > README.md
# Learning & Knowledge Base

> Centralized space for knowledge, lessons, and references across the PARA Workspace.

## Knowledge Areas

| Area | Description |
| :--- | :--- |
| 📚 **[Lessons](./Lessons/README.md)** | Technical lessons, workflows, and solutions extracted from projects (generated by `/learn`). |
| 📦 **[Resources](./Resources/README.md)** | Audit dashboard tracking external codebases, repositories, and study progress (generated by `/resource`). |
EOF
  fi
else
  echo "✅ Directory is already clean. No legacy items found."
fi
